framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    #    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # deleteuser: '%env(MESSENGER_TRANSPORT_DSN_DELETE_USER)%'
      #failed: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
      # sync: 'sync://'
      #sync: '%env(MESSENGER_TRANSPORT_DSN_SEND_WELCOME_MAIL)%'
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN_SEND_WELCOME_MAIL)%'
        retry_strategy:
          max_retries: 3

    routing:
      # Route your messages to the transports
      'App\Message\SendWelcomeEmail': async
      'App\Message\DeleteUser': async
      # 'App\Message\SendWelcomeEmail': sync
      # 'App\Message\DeleteUser': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
