framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async: '%env(MESSENGER_TRANSPORT_DSN_SEND_WELCOME_MAIL)%'
      # deleteuser: '%env(MESSENGER_TRANSPORT_DSN_DELETE_USER)%'
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'
      # sync: '%env(MESSENGER_TRANSPORT_DSN_SEND_WELCOME_MAIL)%'

    routing:
      # Route your messages to the transports
      'App\Message\SendWelcomeEmail': async
      'App\Message\DeleteUser': async
      # 'App\Message\SendWelcomeEmail': sync
      # 'App\Message\DeleteUser': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
