twig:
  default_path: '%kernel.project_dir%/templates'
  file_name_pattern: '*.twig'
  form_themes: [ 'bootstrap_5_layout.html.twig' ]
  globals:
    ga_tracking: 'UA-xxxxx-x'
#        uuid: '@App\Generator\UuidGenerator'

when@test:
  twig:
    strict_variables: true
